# Generated by Django 6.0 on 2025-12-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='story',
            field=models.TextField(blank=True, help_text='A narrative story or introduction to your post'),
        ),
    ]
